version: "3.2"
services:
  database:
    image: kontrollanten/couchdb-hastings:latest
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - type: bind
        source: "$PWD/database/data"
        target: "/opt/couchdb/data"
    ports:
      - 5984:5984

  sandbox: 
    build: .
    depends_on:
      - database
    tty: true
    user: developer
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_DATABASE_PASSWORD=
      - MYSQL_DATABASE_DB=shelters
      - MYSQL_DATABASE_HOST=database
      - CODECOV_TOKEN
      - LINES
      - COLUMNS

    volumes:
      - type: bind
        source: "$HOME/.gitconfig"
        target: /home/developer/.gitconfig
      - type: bind
        source: "$HOME/.vimrc"
        target: /home/developer/.vimrc
      - type: bind
        source: "$HOME/.vim"
        target: /home/developer/.vim
      - type: bind
        source: "$HOME/.ssh"
        target: /home/developer/.ssh
      - type: bind
        source: "$HOME/.zshrc"
        target: /home/developer/.zshrc
      - type: bind
        source: .
        target: /go/src/update-shelters
  functions:
    build: .
    environment:
      - TRAVIS_BRANCH
      - MYSQL_DATABASE_USER
      - MYSQL_DATABASE_PASSWORD
      - MYSQL_DATABASE_DB
      - MYSQL_DATABASE_HOST
      - AWS_ACCESS_KEY_ID  
      - AWS_SECRET_ACCESS_KEY
