version: "3.2"
services:
  database:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE_USER=root
      - MYSQL_ROOT_PASSWORD=shelters
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE_DB=shelters
      - MYSQL_DATABASE_HOST=database
    volumes:
       - type: bind
         source: "$PWD/database/conf/my.cnf"
         target: "/etc/mysql/my.cnf"
    ports:
      - 33060:3306

  functions:
    build: .
    environment:
      - TRAVIS_BRANCH
      - MYSQL_DATABASE_USER
      - MYSQL_DATABASE_PASSWORD
      - MYSQL_DATABASE_DB
      - MYSQL_DATABASE_HOST
      - AWS_ACCESS_KEY_ID  
      - AWS_SECRET_ACCESS_KEY
